"""Collect every non-ASCII character used in the GUI sources into
src/ui_glyphs.inc, so the bold / title fonts (which only load the common
Chinese range to keep the font atlas small) can render all UI text.

Run after changing UI strings:  python tools/gen_ui_glyphs.py
"""
import glob
import os

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "..", "src")
chars = set()
for path in glob.glob(os.path.join(src, "*.cpp")) + glob.glob(os.path.join(src, "*.h")):
    with open(path, encoding="utf-8") as f:
        chars.update(c for c in f.read() if ord(c) > 0x7F)
text = "".join(sorted(chars))
lines = [text[i:i + 40] for i in range(0, len(text), 40)]
with open(os.path.join(src, "ui_glyphs.inc"), "w", encoding="utf-8") as f:
    f.write("// Generated by tools/gen_ui_glyphs.py: every non-ASCII character used in the UI sources.\n")
    f.write("static const char* kUiGlyphs =\n")
    f.write("\n".join('    "%s"' % l.replace("\\", "\\\\").replace('"', '\\"') for l in lines) + ";\n")
print("%d characters -> src/ui_glyphs.inc" % len(chars))
